version: '3.5'

services:
  jenkins:
    image: 'jenkins/jenkins'
    container_name: 'jenkins'
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home

networks:
  jenkinsnet:
    driver: bridge
